### ISSUE TITLE
Permissions and errors

### ISSUE THREAD

**Issue by TzaraDuchamp** [cozplay/cozplay-demos#2]
When I git clone https://github.com/cozplay/cozplay-demos.git I don't have permissions to execute the files. I want to try the apps you wrote. They look great. When I chmod a file of yours it will run, but give errors. For example: 
: command not found
./fortune_teller.py: line 26: syntax error near unexpected token `('
./fortune_teller.py: line 26: `class FotuneTeller(CozGame):'

**Comment by tso7** [comment]
Hey! I think this was because the shebang line was missing. I have added it to the fortune teller script now. Can you try again?

Also, some of the other scripts might be missing this too. You have two options:

**A)** Add the following line to the top of the script you are trying to execute: `#!/usr/bin/env python3`
OR
**B)** Instead of executing the script directly via bash, try executing it using the python command. Examples:
`python fortune_teller.py`
`python code.py`

**Comment by TzaraDuchamp** [comment]
Hey,  thanks for the reply. I'm running this on OS X. Other showcases, like Cozmo Tools, Animation Explorer and Voice Commands do run without permission problems.  

I tried it again after following your suggestions, but still get the permission problem, this is my terminal output: 
$ ./fortune_teller.py
-bash: ./fortune_teller.py: Permission denied
$ python fortune_teller.py
File "fortune_teller.py", line 34
async def run(self, coz_conn):
            ^
SyntaxError: invalid syntax
$ python3 fortune_teller.py
Traceback (most recent call last):
  File "fortune_teller.py", line 7, in <module>
    from common.cozgame import CozGame
ModuleNotFoundError: No module named 'common'

**Comment by tso7** [comment]
Ahh okay. You will need a local copy of the 'common' module. You must download this and place it in the same parent folder under which the other folder/scripts are.

The 'common' module/folder is available in the repository here:
https://github.com/cozplay/cozplay-demos/tree/master/common

**Comment by TzaraDuchamp** [comment]
I cloned the whole Cozplay Master. So that folder is also present. I tried to symlink to the folder too and that also doesn't work.

**Comment by tso7** [comment]
I think I know what's happening but let me replicate it and give you a reliable solution. I'm out of town until Sunday, will test it after that and provide an update.

**Comment by tso7** [comment]
Sorry for the delay in my reply. If this issue is still occurring, you can resolve it by adding the cloned folder to your PYTHONPATH value. This can be done using the following command:

`export PYTHONPATH="${PYTHONPATH}:/path/to/cozplay-demos/folder"`

You can check the value by:
`echo $PYTHONPATH`

Once this is done, the directory should be marked for python executables and the modules will be recognized.
